import React from "react";
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { Button } from '@/components/ui/Button';

function iconAi() {return <svg width="32" height="32" viewBox="0 0 32 32"><circle cx="16" cy="16" r="14" fill="#06B6D4"/><path d="M9 23c2.5-6 10.5-10 14-4" stroke="#fff" strokeWidth="2"/><circle cx="12" cy="15" r="2" fill="#fff"/></svg>;}
function iconCheck() {return <svg width="32" height="32"><circle cx="16" cy="16" r="14" fill="#10B981"/><path d="M11 16l3 3 6-6" stroke="#fff" strokeWidth="2"/></svg>;}
function iconCam() {return <svg width="32" height="32"><circle cx="16" cy="16" r="14" fill="#3B82F6"/><rect x="10" y="14" width="12" height="7" rx="2" fill="#fff"/><rect x="15" y="10" width="2" height="4" rx="1" fill="#06B6D4"/></svg>;}
function iconPin() {return <svg width="32" height="32"><circle cx="16" cy="16" r="14" fill="#1E40AF"/><path d="M16 26c3.31 0 6-2.69 6-6S16 8 16 8s-6 5.69-6 12 2.69 6 6 6Z" fill="#fff"/></svg>;}
function iconChat() {return <svg width="32" height="32"><circle cx="16" cy="16" r="14" fill="#F97316"/><rect x="10" y="18" width="12" height="6" rx="3" fill="#fff"/><circle cx="16" cy="16" r="5" fill="#fff"/></svg>;}
function iconShield() {return <svg width="32" height="32"><circle cx="16" cy="16" r="14" fill="#0A2463"/><path d="M10 12c0 8 6 9 6 9s6-1 6-9l-6-3-6 3Z" fill="#3B82F6"/><path d="M16 19v2.5" stroke="#fff" strokeWidth="2"/></svg>;}
const features=[{icon:iconAi(),title:'AI-POWERED SEARCH',desc:'Tell us what you need. Our AI finds perfect matches in seconds.'},{icon:iconCheck(),title:'VERIFIED LISTINGS ONLY',desc:'Every property verified before publication. Zero fake listings.'},{icon:iconCam(),title:'VIRTUAL TOURS',desc:'Explore properties from your phone with 360° virtual tours.'},{icon:iconPin(),title:'NEIGHBORHOOD INSIGHTS',desc:'Schools, hospitals, transportation—know before you visit.'},{icon:iconChat(),title:'DIRECT CONNECTION',desc:'No middleman fees. Connect straight to verified owners.'},{icon:iconShield(),title:'FRAUD PROTECTION',desc:'Built-in safeguards against scams and fake documents.'}];
const steps=[{num:1,head:'SEARCH',body:'Enter location, type (rent/buy), and budget. AI finds matches.'},{num:2,head:'BROWSE',body:'Scroll verified listings with photos, virtual tours, and insights.'},{num:3,head:'CONNECT',body:'Request viewing or make offer. Owner responds within 24 hours.'},{num:4,head:'MOVE IN',body:'Complete secure transaction. Move into your perfect home.'}];
const testimonials=[{quote:'I found my apartment in 48 hours using Propabridge. Everything verified, no agent fees, no stress.','name':'Early Beta User, Abuja'},{quote:'As a landlord, Propabridge connected me with serious tenants instantly. The vetting process protects both sides.','name':'Property Owner, Lagos'}];
export default function PropabridgePage(){return(<><Header/><main className="max-w-5xl mx-auto py-12 px-4"><section className="mb-10 text-center"><h1 className="font-heading text-4xl font-bold text-primary-900 mt-2 mb-3">Find Your Home in Minutes, Not Weeks</h1><h2 className="text-xl text-gray-700 mb-4">Nigeria's AI-powered property marketplace connecting renters and buyers with verified landlords and developers.</h2><div className="flex flex-wrap gap-4 justify-center mt-6"><Button variant="primary" size="lg" href="https://app.propabridge.com">Try Propabridge</Button><Button variant="secondary" size="lg" href="#">Watch Demo</Button></div></section>
<section className="mb-14"><h3 className="font-heading text-2xl text-primary-700 font-bold mb-7 text-center">Features</h3><div className="grid md:grid-cols-3 gap-8">{features.map(f=>(<div key={f.title} className="rounded-xl bg-primary-100/80 dark:bg-primary-900/20 p-6 flex flex-col items-center text-center shadow"><div className="mb-3">{f.icon}</div><div className="font-heading font-bold text-md text-primary-900 dark:text-white mb-2">{f.title}</div><div className="text-xs text-gray-700 dark:text-primary-100 opacity-80">{f.desc}</div></div>))}</div></section>
<section className="mb-14"><h3 className="font-heading text-2xl text-primary-700 font-bold mb-7 text-center">How It Works</h3><div className="flex flex-col md:flex-row justify-center gap-6">{steps.map(s=>(<div key={s.head} className="flex-1 bg-white dark:bg-primary-900/30 rounded-xl p-6 shadow flex flex-col items-center"><div className="mb-2 w-10 h-10 flex items-center justify-center font-bold text-xl rounded-full bg-accent-cyan/80 text-white">{s.num}</div><div className="font-semibold mb-1 text-primary-900 dark:text-white">{s.head}</div><div className="text-xs text-gray-700 dark:text-primary-100 opacity-85 text-center">{s.body}</div></div>))}</div><div className="flex justify-center mt-8"><Button variant="primary" size="md" href="https://app.propabridge.com">Start Searching</Button></div></section>
<section className="mb-14"><h3 className="font-heading text-2xl text-primary-700 font-bold mb-7 text-center">Testimonials</h3><div className="grid md:grid-cols-2 gap-8">{testimonials.map(t=>(<div key={t.name} className="rounded-xl bg-primary-100/80 dark:bg-primary-900/20 p-7 flex flex-col items-center shadow"><div className="w-14 h-14 rounded-full bg-accent-cyan/30 flex items-center justify-center mb-2 text-xl font-bold text-primary-700">"</div><div className="mb-2 text-gray-800 dark:text-primary-100 italic">{t.quote}</div><div className="text-xs text-primary-900 dark:text-primary-100 font-semibold mt-1">{t.name}</div></div>))}</div></section>
<section className="mb-14"><h3 className="font-heading text-2xl text-primary-700 font-bold mb-7 text-center">Pricing</h3><div className="grid md:grid-cols-2 gap-8"><div className="rounded-xl bg-primary-100/90 dark:bg-primary-900/20 p-6 shadow flex flex-col items-center text-center border border-accent-cyan/30"><div className="mb-2 font-heading font-bold text-primary-900">FOR RENTERS/BUYERS</div><div className="mb-2 text-accent-cyan text-lg font-bold">100% FREE</div><ul className="text-xs text-gray-900 dark:text-primary-100 opacity-80 list-disc mb-3 text-left"><li>Unlimited searches</li><li>Property verification included</li><li>Direct owner contact</li><li>Virtual tours</li></ul></div><div className="rounded-xl bg-primary-100/90 dark:bg-primary-900/20 p-6 shadow flex flex-col items-center text-center border border-primary-500/20"><div className="mb-2 font-heading font-bold text-primary-900">FOR LANDLORDS/DEVELOPERS</div><ul className="mb-2 text-xs text-left text-gray-900 dark:text-primary-100 opacity-80 list-disc"><li>Premium Listing: <span className="text-primary-700">₦50,000-₦200,000</span> (enhanced visibility)</li><li>Commission: <span className="text-primary-700">5-10%</span> on successful transaction</li><li>Subscription Plans: <span className="text-primary-700">Coming Soon</span></li></ul></div></div><div className="flex justify-center mt-7"><Button variant="primary" href="/contact?type=landlord">List Your Property</Button></div></section></main><Footer/></>);}
