import React from "react";
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { Button } from '@/components/ui/Button';

function SatelliteDetectionIcon() {return <svg width="34" height="34"><rect x="6" y="20" width="22" height="8" rx="4" fill="#06B6D4"/><ellipse cx="17" cy="17" rx="7" ry="7" fill="#fff"/><rect x="15" y="7" width="4" height="10" rx="1" fill="#DBEAFE"/></svg>;}
function DashboardIcon() {return <svg width="34" height="34"><rect x="8" y="14" width="18" height="12" rx="4" fill="#1E40AF"/><circle cx="17" cy="23" r="7" fill="#06B6D4"/><rect x="14" y="5" width="6" height="9" rx="1.5" fill="#F97316"/></svg>;}
function PortalIcon() {return <svg width="34" height="34"><rect x="7" y="7" width="20" height="20" rx="6" fill="#3B82F6"/><rect x="14" y="14" width="6" height="6" rx="2" fill="#fff"/></svg>;}
export default function FastFind360Page(){return(<><Header/>
<main className="max-w-5xl mx-auto py-12 px-4">
{/* Hero */}
<section className="mb-10 text-center"><h1 className="font-heading text-4xl font-bold text-primary-900 mt-2 mb-3">Making Nigeria's ₦2 Trillion Invisible Problem Visible</h1><h2 className="text-xl text-gray-700 mb-4">Government revenue intelligence platform powered by satellite AI. Recover lost tax revenue. Map the unmapped.</h2><div className="flex flex-wrap gap-4 justify-center mt-6"><Button variant="primary" size="lg" href="/contact?type=gov">Schedule Government Demo</Button><Button variant="secondary" size="lg" href="#">View Case Study</Button></div></section>
{/* Problem Stats */}
<section className="mb-12"><div className="grid md:grid-cols-3 gap-8"><div className="rounded-xl bg-primary-100/90 p-6 text-center"><div className="font-heading text-2xl text-accent-cyan mb-1">60%</div><div className="font-semibold mb-2 text-primary-900">Informal Development</div><div className="text-xs text-gray-700">Billions in buildings and spaces that don't officially exist</div></div><div className="rounded-xl bg-primary-100/90 p-6 text-center"><div className="font-heading text-2xl text-accent-cyan mb-1">₦2T+</div><div className="font-semibold mb-2 text-primary-900">Annual Loss</div><div className="text-xs text-gray-700">Revenue that slips through the cracks of manual surveying</div></div><div className="rounded-xl bg-primary-100/90 p-6 text-center"><div className="font-heading text-2xl text-accent-cyan mb-1">3-5yrs</div><div className="font-semibold mb-2 text-primary-900">Outdated Survey Data</div><div className="text-xs text-gray-700">By the time surveys finish, cities have already changed</div></div></div></section>
{/* Solution Features */}
<section className="mb-12"><h3 className="font-heading text-2xl text-primary-700 font-bold mb-7 text-center">The Solution</h3><div className="grid md:grid-cols-3 gap-8 text-center">{[{icon:SatelliteDetectionIcon(),head:'SATELLITE DETECTION',desc:'Automated identification of ALL properties — including informal settlements, new constructions, and illegal structures — using advanced satellite imagery and AI.'},{icon:DashboardIcon(),head:'ADMIN DASHBOARD',desc:'Centralized command center for government officials to view, flag, and manage unregistered or illegal structures. Streamlined enforcement workflows.'},{icon:PortalIcon(),head:'CITIZEN VERIFICATION PORTAL',desc:'User-friendly portal where citizens verify property details and report discrepancies. Crowdsourced transparency.'}].map(s=>(<div key={s.head} className="rounded-xl bg-white dark:bg-primary-900/60 drop-shadow p-7 flex flex-col items-center"><div className="mb-3">{s.icon}</div><div className="font-heading font-bold text-md text-primary-900 dark:text-white mb-2">{s.head}</div><div className="text-xs text-gray-700 dark:text-primary-100 opacity-70 text-center">{s.desc}</div></div>))}</div></section>
{/* Market Opportunity */}
<section className="mb-14"><h3 className="font-heading text-2xl text-primary-700 font-bold mb-3">Market Opportunity</h3><ul className="list-disc text-sm mb-1 pl-7 text-gray-800"><li>Real Estate Market: $2.25 trillion</li><li>Lost Property Tax: ₦2T+ annually (est.)</li><li>774 LGAs, 36 states Addressable</li></ul><div className="text-xs mt-3 text-gray-700">B2G Licensing, API/Data Access, Freemium Citizen Services</div></section>
{/* Tech Stack */}
<section className="mb-14"><h3 className="font-heading text-2xl text-primary-700 font-bold mb-3">Technical Stack</h3><div className="text-base text-primary-900 dark:text-primary-100 mb-1">FRONTEND: React.js &nbsp; | &nbsp; BACKEND: Node.js &nbsp; | &nbsp; GEOSPATIAL: Mapbox, Google Earth Engine &nbsp; | &nbsp; SATELLITE DATA: NIGCOMSAT feeds</div><div className="text-xs text-gray-700">AI/ML: Custom building detection models. Roadmap: Predictive land change, asset tracking, climate risk layers</div></section>
{/* Pilot Results */}
<section className="mb-14"><h3 className="font-heading text-2xl text-primary-700 font-bold mb-4">Pilot Results: Gombe State</h3><ul className="list-disc text-sm mb-2 pl-7 text-gray-800"><li>2.3M+ properties detected</li><li>94% accuracy vs. ground truth</li><li>₦500B+ revenue potential identified</li><li>85% reduction in surveying time</li><li>70% cost savings vs. traditional methods</li></ul><div className="flex justify-center mt-8"><svg width="180" height="75" viewBox="0 0 180 75" fill="none"><ellipse cx="90" cy="42" rx="82" ry="28" fill="#06B6D4" fillOpacity=".18"/><rect x="55" y="32" width="70" height="20" rx="8" fill="#3B82F6" fillOpacity=".18"/></svg></div></section>
{/* CTA */}
<section className="mb-8 text-center"><h3 className="font-heading text-2xl text-primary-700 font-bold mb-4">Ready to Unlock Your State's Hidden Revenue?</h3><div className="mb-3 text-gray-800 dark:text-primary-100">Join forward-thinking governments already piloting FastFind360.</div><div className="flex flex-wrap gap-4 justify-center"><Button variant="primary" size="md" href="#">Schedule a Demo</Button><Button variant="secondary" size="md" href="#">Download White Paper</Button></div></section>
</main><Footer/></>);}
